apiVersion: v1
kind: PersistentVolume
metadata:
  name: task5-local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/storage
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task5-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-storage-deployment
  labels:
    app: local-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-storage
  template:
    metadata:
      labels:
        app: local-storage
    spec:
      containers:
        # Писатель
        - name: busybox-writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              while true; do
                echo "$(date): Data from busybox" >> /shared/output.log;
                sleep 5;
              done
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
        # Читатель
        - name: multitool-reader
          image: wbitt/network-multitool
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Reader started. Watching /shared/output.log...";
              tail -f /shared/output.log;
          volumeMounts:
            - name: shared-storage
              mountPath: /shared
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: task5-pvc
