apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-service
spec:
  selector:
    app: {{ include "myapp.fullname" . }}-app
  ports:
  - port: 80
    targetPort: {{ .Values.app.port }}
