---
all:
  hosts:
    nexus2:
      ansible_host: 89.169.172.152
  children:
    nexus:
      hosts:
        nexus2:
  vars:
    ansible_connection_type: paramiko
    ansible_user: roman
    ansible_ssh_private_key_file: ~/.ssh/ssh-rsa
    ansible_host_key_checking: false